[Resolve #966] Add support for J2 Environment configuration
Sceptre/sceptre pull request #1079
Opened 2021-08-07 16:15 UTC by mrowlingfox

This PR adds support for configuring the Jinja2 Environment.

`j2_environment` can be defined within a stack config and maps to 

E.g

```yaml
j2_environment:
  extensions:
    - jinja2.ext.i18n
    - jinja2.ext.do
  trim: 
```

## PR Checklist

- [x] Wrote a good commit message & description [see guide below].
- [x] Commit message starts with `[Resolve #issue-number]`.
- [x] Added/Updated unit tests.
- [ ] Added/Updated integration tests (if applicable).
- [x] All unit tests (`make test`) are passing.
- [x] Used the same coding conventions as the rest of the project.
- [x] The new code passes pre-commit validations (`pre-commit run --all-files`).
- [] The PR relates to _only_ one subject with a clear title.
      and description in grammatically correct, complete sentences.

## Approver/Reviewer Checklist

- [ ] Before merge squash related commits.

## Other Information

[Guide to writing a good commit](http://chris.beams.io/posts/git-commit/)

2021-08-07 16:18 UTC, mrowlingfox commented
Also resolves #952

2021-08-08 21:14 UTC, shanemacphillamy approved these changes
LGTM.

2021-08-10 16:28 UTC, zaro0508 requested changes
I like it @mrowlingfox, kill two birds with one stone.  Just need slight fixes to the docs and i think it's good to go.

2021-08-10 16:28 UTC, zaro0508 commented on docs/_source/docs/stack_group_config.rst
> +    - jinja2.ext.do
would you mind giving an example of passing in a few other [jinja2 environment options](https://jinja.palletsprojects.com/en/3.0.x/api/#jinja2.Environment) ?

2021-08-11 00:07 UTC, mrowlingfox commented on docs/_source/docs/stack_group_config.rst
> +```yaml
You're right, it does! I just copy pasted from https://github.com/Sceptre/sceptre/blob/c7103450e4c70135723e8c8d9a3e98ad5e762f72/docs/_source/docs/faq.rst#L103 

Looking at the docs that doesn't seem to render correctly, so I'll update both.

2021-08-11 00:54 UTC, mrowlingfox commented on docs/_source/docs/stack_group_config.rst
> +It's converted to keyword arguments then passed to [jinja2.Environment](https://jinja.palletsprojects.com/en/2.11.x/api/#jinja2.Environment).
Correct, it can

E.g `--var j2_environment="{\"extensions\":[\"jinja2_ansible_filters.AnsibleCoreFiltersExtension\"]}"`

2021-08-13 17:54 UTC, zaro0508 approved these changes

2021-08-13 17:54 UTC, zaro0508 commented on docs/_source/docs/faq.rst
> +.. code-block:: yaml
thanks for fixing these

2021-08-14 06:06 UTC, mrowlingfox commented
Thanks @zaro0508  Looking forward to seeing this merged 😄 Will be a very useful feature for us

2021-08-16 14:01 UTC, merged