[Resolve #1096] Gracefully executing SAM Change sets
Sceptre/sceptre pull request #1099
Opened 2021-09-19 16:38 UTC by jfalkenstein

[Your PR description here]

## PR Checklist

- [ ] Wrote a good commit message & description [see guide below].
- [ ] Commit message starts with `[Resolve #issue-number]`.
- [ ] Added/Updated unit tests.
- [ ] Added/Updated integration tests (if applicable).
- [ ] All unit tests (`make test`) are passing.
- [ ] Used the same coding conventions as the rest of the project.
- [ ] The new code passes pre-commit validations (`pre-commit run --all-files`).
- [ ] The PR relates to _only_ one subject with a clear title.
      and description in grammatically correct, complete sentences.

## Approver/Reviewer Checklist

- [ ] Before merge squash related commits.

## Other Information

[Guide to writing a good commit](http://chris.beams.io/posts/git-commit/)

2021-09-19 16:45 UTC, jfalkenstein commented on integration-tests/features/execute-change-set.feature
> +    Then stack "2/A" has change set "A" in "FAILED" state
It turns out we didn't have any existing integration test for the other scenario that wasn't SAM. It felt important to have coverage for both types of message.

2021-09-19 16:45 UTC, jfalkenstein commented on integration-tests/steps/stacks.py
> +        ]
You can't build a SAM stack without capabilities.

2021-09-19 16:47 UTC, jfalkenstein commented on tests/test_actions.py
> +        assert result == 0
We didn't have a unit test for this scenario, so I made sure we had one.

2021-09-19 16:49 UTC, jfalkenstein commented
@zaro0508, there hasn't yet been comment on #1096, but getting this issue resolved is going to be pretty important for my company and our plans to use Sceptre with SAM. I see that you're one of the more active maintainers on Spectre. What is it I need to do to move this forward?

2021-09-20 17:09 UTC, zaro0508 commented
@jfalkenstein I don't have any issues with this change but I also don't use CFN changesets.  To move this forward you'll want to resolve the conflicts and then have it reviewed by someone that does care about changesets.  Maybe @alexharv074  or @mrowlingfox might be interested in reviewing this?

2021-09-21 15:44 UTC, alexharv074 commented on sceptre/plan/actions.py
> +    def change_set_creation_failed_due_to_no_changes(self, reason: str) -> bool:
I think that consistency with the rest of the code base here would mean we don't provide type hints—as much as I also like type hints! Normally, rather, the return type is indicated in the doc string. (See elsewhere in the file for examples.) (I daresay `no_change_substrings` below could be a list to be more consistent too, although I didn't look at it closely and have no strong opinion.)

2021-09-21 15:46 UTC, alexharv074 requested changes
Minor inconsistency with the rest of the code base I think should be fixed up, otherwise LGTM.

2021-09-21 16:16 UTC, alexharv074 approved these changes
Lgtm

2021-09-22 14:20 UTC, jfalkenstein commented
@zaro0508 now that this has been approved by @alexharv074, what more must be done to this and the issue to move this along?

2021-09-22 17:56 UTC, zxiiro approved these changes

2021-09-24 16:41 UTC, merged