Setup to build docs on readthedocs.org
Sceptre/sceptre pull request #1105
Opened 2021-09-21 18:28 UTC by zaro0508

This is to partially resolve issue #1098.

We plan to move sceptre docs away from hosting on a cloudreach
domain to https://readthedocs.org/project/sceptre

This PR builds the sphinx docs on readthedocs.org

2021-09-21 18:31 UTC, ngfgrant commented
What are the benefits of moving away from GitHub pages?

2021-09-21 18:39 UTC, zxiiro approved these changes

2021-09-21 18:50 UTC, zaro0508 commented
@ngfgrant github pages is markdown format while the sceptre docs is reStructuredText format

2021-09-21 18:55 UTC, ngfgrant commented
Oh right - the docs are currently being served from GitHub Pages (the format of the content doesn't matter as it's all generated to html in the end).

2021-09-21 18:58 UTC, ngfgrant commented
To change the url you just need to edit the CNAME file here https://github.com/Sceptre/sceptre.github.io/tree/master

Alternatively, just remove it and you can access the docs at sceptre.github.io

2021-09-21 21:08 UTC, zaro0508 commented
thanks @ngfgrant.    can we just replace cloudreach domain in the CNAME with the domain you've setup @tarkatronic ?

2021-09-21 23:59 UTC, craighurley commented
> Alternatively, just remove it and you can access the docs at sceptre.github.io

I didn't realise that was an option.  The discussion about registering a domain for the project was mainly focused on a domain for the docs.  If the docs can be accissible from sceptre.github.io, isn't that good enough and removes the need for maintaining a domain?

2021-09-22 07:32 UTC, ngfgrant commented
@zaro0508 yep that is correct. Alternatively, as Craig said we can just use the GitHub provided domain.

2021-09-22 12:09 UTC, zxiiro commented
> What are the benefits of moving away from GitHub pages?

One of the nice things that ReadTheDocs provides as a built-in UI and support for multiple versions of docs. Switching to GitHub pages would mean we lose that right?

According to https://sceptre.cloudreach.com/ on the bottom left, it loooks like CloudReach's Sceptre docs are hosoted through ReadTheDocs right now or am I missing something?

2021-09-22 12:13 UTC, ngfgrant commented
@zxiiro  we wouldn't be switching to GitHub Pages as we are already using it. We also maintain versioned docs already.. 

Sceptre docs are "hosted" at https://github.com/Sceptre/sceptre.github.io

2021-09-22 13:09 UTC, zxiiro commented
> @zxiiro  we wouldn't be switching to GitHub Pages as we are already using it. We also maintain versioned docs already.. 
> 
> 
> 
> Sceptre docs are "hosted" at https://github.com/Sceptre/sceptre.github.io

Interesting. I guess I haven't seen a readthedocs theme deployment outside of readthedocs which was what threw me off. Good to know it's possible.

2021-09-22 13:17 UTC, ngfgrant requested changes
I would leave this for now as there is nothing wrong or restrictive about the current set up.

2021-09-22 13:36 UTC, tarkatronic commented
> > Alternatively, just remove it and you can access the docs at sceptre.github.io
> 
> I didn't realise that was an option. The discussion about registering a domain for the project was mainly focused on a domain for the docs. If the docs can be accissible from sceptre.github.io, isn't that good enough and removes the need for maintaining a domain?

The initial discussion around registering the domain was to get the GitHub org verified, and eventually to be able to become a verified publisher, specifically for the GitHub Action.

The domain itself can be pointed at either GitHub Pages or ReadTheDocs. That part doesn't really matter. Although I would still recommend using RTD, as a way to reduce complexity. That build process right now is managed by a series of self-authored scripts which could very easily break at any time, whereas using RTD is simply a matter of setting up a config and installing the application on GitHub.

I personally advocate for any tooling that can reduce complexity in a build pipeline.

2021-09-22 14:50 UTC, ngfgrant commented
> The initial discussion around registering the domain was to get the GitHub org verified, and eventually to be able to become a verified publisher, specifically for the GitHub Action.
> 
> The domain itself can be pointed at either GitHub Pages or ReadTheDocs. That part doesn't really matter. Although I would still recommend using RTD, as a way to reduce complexity. That build process right now is managed by a series of self-authored scripts which could very easily break at any time, whereas using RTD is simply a matter of setting up a config and installing the application on GitHub.
> 
> I personally advocate for any tooling that can reduce complexity in a build pipeline.

IIRC the factors around original decision for how we handled docs were: 

- reduce "tooling sprawl"
- remove dependency on 3rd party service and any incompatible version changes (e.g. RTD v1 vs v2). 
- the flexibility/control of having specific docs available (e.g. we wanted to keep some of the old v1 docs alive). 

The scripts could break at any time, but in reality they haven't since they were published 2 years ago... famous last words eh?

Ideally, we would reduce tool sprawl further by bringing the CI/CD to GitHub too... but that is another story. 

A side note having these sorts of suggestions is fine but I would say they add limited value. Thanks to me (and some others) bigger problems exist in Sceptre - such as useful error messages or more meaningful debug statements. If we have people that are engaged with the project it would be good to get stuck in to the core concerns rather than around the periphery.

2021-09-22 14:55 UTC, tarkatronic commented
> Ideally, we would reduce tool sprawl further by bringing the CI/CD to GitHub too... but that is another story.

We have definitely talked about moving to GitHub Actions! The complexity of CircleCI has been quite a frustration, especially in #1035. A lot of the problems I've had to deal with are very specific to CircleCI, and (in my experience) don't exist, or manifest the same, on GitHub Actions.

> A side note having these sorts of suggestions is fine but I would say they add limited value. Thanks to me (and some others) bigger problems exist in Sceptre - such as useful error messages or more meaningful debug statements. If we have people that are engaged with the project it would be good to get stuck in to the core concerns rather than around the periphery.

I agree there are definitely improvements to be made in the core, but the tooling around the project is a place where people like myself, less intimately familiar with the core, can help immediately.

2021-09-22 14:57 UTC, tarkatronic commented
The other goal here is to lend further legitimacy to the project; having an official domain (which is totally free btw) and that little verified checkmark wherever possible can tend to add to that. I know that things like that give me a little more confidence in projects when I see them.

Plus, selfishly, my employer only allows us to use GitHub Actions from verified publishers. So I'm hoping that the Sceptre action can become one of those viable for use.

2021-09-22 16:08 UTC, ngfgrant commented
100% onboard for new domain and GitHub Action sounds very cool - hopefully we can utilise the existing Dockerfile?

2021-09-22 16:40 UTC, zaro0508 commented
> A side note having these sorts of suggestions is fine but I would say they add limited value. Thanks to me (and some others) bigger problems exist in Sceptre - such as useful error messages or more meaningful debug statements. If we have people that are engaged with the project it would be good to get stuck in to the core concerns rather than around the periphery.

2021-09-22 17:00 UTC, closed without merging

2021-09-22 18:18 UTC, tarkatronic commented
> 100% onboard for new domain and GitHub Action sounds very cool - hopefully we can utilise the existing Dockerfile?

The goal is that the `Dockerfile` in this project will be able to translate over with no problem. The only modifications are in #1035; in there, I have changed it to a multi-stage build, utilizing Poetry to install dependencies. In this way we eliminate the fragmentation of requirements specifications (`setup.py`, `requirements/dev.txt`, and `requirements/prod.txt`) and, with the multi-stage build, it will ideally generate a smaller image overall!

If you're referring to the `sceptre-circleci` Docker image, then we should actually be able to fully eliminate that and just use the default GitHub Actions runner images 🤞🏻 -- at least, that's the hope.

And I'm super excited to work on that transition, if I can ever get the Poetry work finalized and landed!